_JAVA_AWT_WM_NONREPARENTING=1
_JAVA_OPTIONS="-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true"
XDG_CURRENT_DESKTOP=${XDG_CURRENT_DESKTOP:-sway}
XDG_SESSION_TYPE=${XDG_SESSION_TYPE:-wayland}
SDL_VIDEODRIVER=wayland
QT_QPA_PLATFORMTHEME=qt5ct
